openapi: 3.0.0
info:
  title: API-Rimac
  version: '1.0'
servers:
  - url: 'https://rimac-aws.xyz'
paths:
  /todo:
    get:
      summary: todo
      tags: []
      responses: {}
      operationId: get-todo
components:
  schemas: {}
